setwd("C:/Users/ivanr/Master/clases/Mod/Proyecto")
library(tidyverse)
library(brms)
db1 <- read.delim("L_multiflorum.csv", sep = ",")
db1 <- subset(db1, select= -Tiller)
str(db1)
db1[,3:5] <- lapply(db1[,3:5], factor)
str(db1)
db <- db1 %>% 
  mutate(Ozono = if_else(Ozone == 1, "Ozono", "Sin Ozono"),
         Endófitos= if_else(Endophyte == 1, "Endófitos", "Sin Endófitos"),
         Herbivoría= if_else(Aphid == 1, "Áfidos", "Sin Áfidos"))

individuos <- db %>% 
  group_by(Ozono, Endófitos, Herbivoría) %>% 
  summarise(Indviduos= n(), Media=mean(`Biomass`), SD= sd(`Biomass`))

mod0.ln <- brm(Biomass ~ 1, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod0.ln, file = "mod0.ln.RData")
mod1.ln <- brm(Biomass ~ Ozone, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod1.ln, file = "mod1.ln.RData")
mod1.re.ln.a <- brm(Biomass ~ Ozone + (1 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod1.re.ln.a, file = "mod1.ln.a.RData")
mod1.re.ln.b <- brm(Biomass ~ Ozone + (0 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod1.re.ln.b, file = "mod1.ln.b.RData")
mod1.re.ln.c <- brm(Biomass ~ Ozone + (1 | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod1.re.ln.c, file = "mod1.ln.c.RData")

mod2.ln <- brm(Biomass ~ Aphid, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod2.ln, file = "mod2.ln.RData")
mod2.re.ln.a <- brm(Biomass ~ Aphid + (1 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod2.re.ln.a, file = "mod2.re.ln.a.RData")
mod2.re.ln.b <- brm(Biomass ~ Aphid + (0 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod2.re.ln.b, file = "mod2.re.ln.b.RData")
mod2.re.ln.c <- brm(Biomass ~ Aphid + (1 | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod2.re.ln.c, file = "mod2.re.ln.c.RData")

mod3.ln <- brm(Biomass ~ Endophyte, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod3.ln, file = "mod3.ln.RData")
mod3.re.ln.a <- brm(Biomass ~ Endophyte + (1 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod3.re.ln.a, file = "mod3.re.ln.a.RData")
mod3.re.ln.b <- brm(Biomass ~ Endophyte + (0 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod3.re.ln.b, file = "mod3.re.ln.b.RData")
mod3.re.ln.c <- brm(Biomass ~ Endophyte + (1 | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod3.re.ln.c, file = "mod3.re.ln.c.RData")

mod4.ln <- brm(Biomass ~ Ozone + Aphid, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod4.ln, file = "mod4.ln.RData")
mod4.re.ln.a <- brm(Biomass ~ Ozone + Aphid + (1 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod4.re.ln.a, file = "mod4.re.ln.a.RData")
mod4.re.ln.b <- brm(Biomass ~ Ozone + Aphid + (0 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod4.re.ln.b, file = "mod4.re.ln.b.RData")
mod4.re.ln.c <- brm(Biomass ~ Ozone + Aphid + (1 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod4.re.ln.c, file = "mod4.re.ln.c.RData")
mod4.re.ln.d <- brm(Biomass ~ Ozone + Aphid + (0 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod4.re.ln.d, file = "mod4.re.ln.d.RData")
mod4.re.ln.e <- brm(Biomass ~ Ozone + Aphid + (1 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod4.re.ln.e, file = "mod4.re.ln.e.RData")
mod4.re.ln.f <- brm(Biomass ~ Ozone + Aphid + (0 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod4.re.ln.f, file = "mod4.re.ln.f.RData")
mod4.re.ln.g <- brm(Biomass ~ Ozone + Aphid + (1 | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod4.re.ln.g, file = "mod4.re.ln.g.RData")

mod5.ln <- brm(Biomass ~ Ozone + Endophyte, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod5.ln, file = "mod5.ln.RData")
mod5.re.ln.a <- brm(Biomass ~ Ozone + Endophyte + (1 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod5.re.ln.a, file = "mod5.re.ln.a.RData")
mod5.re.ln.b <- brm(Biomass ~ Ozone + Endophyte + (0 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod5.re.ln.b, file = "mod5.re.ln.b.RData")
mod5.re.ln.c <- brm(Biomass ~ Ozone + Endophyte + (1 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod5.re.ln.c, file = "mod5.re.ln.c.RData")
mod5.re.ln.d <- brm(Biomass ~ Ozone + Endophyte + (0 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod5.re.ln.d, file = "mod5.re.ln.d.RData")
mod5.re.ln.e <- brm(Biomass ~ Ozone + Endophyte + (1 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod5.re.ln.e, file = "mod5.re.ln.e.RData")
mod5.re.ln.f <- brm(Biomass ~ Ozone + Endophyte + (0 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod5.re.ln.f, file = "mod5.re.ln.f.RData")
mod5.re.ln.g <- brm(Biomass ~ Ozone + Endophyte + (1 | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod5.re.ln.g, file = "mod5.re.ln.g.RData")

mod6.ln <- brm(Biomass ~ Aphid + Endophyte, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod6.ln, file = "mod6.ln.RData")
mod6.re.ln.a <- brm(Biomass ~ Aphid + Endophyte + (1 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod6.re.ln.a, file = "mod6.re.ln.a.RData")
mod6.re.ln.b <- brm(Biomass ~ Aphid + Endophyte + (0 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod6.re.ln.b, file = "mod6.re.ln.b.RData")
mod6.re.ln.c <- brm(Biomass ~ Aphid + Endophyte + (1 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod6.re.ln.c, file = "mod6.re.ln.c.RData")
mod6.re.ln.d <- brm(Biomass ~ Aphid + Endophyte + (0 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod6.re.ln.d, file = "mod6.re.ln.d.RData")
mod6.re.ln.e <- brm(Biomass ~ Aphid + Endophyte + (1 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod6.re.ln.e, file = "mod6.re.ln.e.RData")
mod6.re.ln.f <- brm(Biomass ~ Aphid + Endophyte + (0 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod6.re.ln.f, file = "mod6.re.ln.f.RData")
mod6.re.ln.g <- brm(Biomass ~ Aphid + Endophyte + (1 | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod6.re.ln.g, file = "mod6.re.ln.g.RData")

mod7.ln <- brm(Biomass ~ Ozone + Aphid + Endophyte, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.ln, file = "mod7.ln.RData")
mod7.re.ln.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Ozone + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.a, file = "mod7.re.ln.a.RData")
mod7.re.ln.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.b, file = "mod7.re.ln.b.RData")
mod7.re.ln.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.c, file = "mod7.re.ln.c.RData")
mod7.re.ln.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.d, file = "mod7.re.ln.d.RData")
mod7.re.ln.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Ozone + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.e, file = "mod7.re.ln.e.RData")
mod7.re.ln.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.f, file = "mod7.re.ln.f.RData")
mod7.re.ln.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.g, file = "mod7.re.ln.g.RData")
mod7.re.ln.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.h, file = "mod7.re.ln.h.RData")
mod7.re.ln.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.i, file = "mod7.re.ln.i.RData")
mod7.re.ln.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.j, file = "mod7.re.ln.j.RData")
mod7.re.ln.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.k, file = "mod7.re.ln.k.RData")
mod7.re.ln.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.l, file = "mod7.re.ln.l.RData")
mod7.re.ln.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.m, file = "mod7.re.ln.m.RData")
mod7.re.ln.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod7.re.ln.n, file = "mod7.re.ln.n.RData")


mod8.ln <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.ln, file = "mod8.ln.RData")
mod8.re.ln.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.a, file = "mod8.re.ln.a.RData")
mod8.re.ln.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.b, file = "mod8.re.ln.b.RData")
mod8.re.ln.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.c, file = "mod8.re.ln.c.RData")
mod8.re.ln.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.d, file = "mod8.re.ln.d.RData")
mod8.re.ln.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.e, file = "mod8.re.ln.e.RData")
mod8.re.ln.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.f, file = "mod8.re.ln.f.RData")
mod8.re.ln.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.f, file = "mod8.re.ln.f.RData")
mod8.re.ln.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.h, file = "mod8.re.ln.h.RData")
mod8.re.ln.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.i, file = "mod8.re.ln.i.RData")
mod8.re.ln.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.j, file = "mod8.re.ln.j.RData")
mod8.re.ln.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.k, file = "mod8.re.ln.k.RData")
mod8.re.ln.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.l, file = "mod8.re.ln.l.RData")
mod8.re.ln.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.m, file = "mod8.re.ln.m.RData")
mod8.re.ln.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.n, file = "mod8.re.ln.n.RData")
mod8.re.ln.o <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Aphid + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.o, file = "mod8.re.ln.o.RData")
mod8.re.ln.p <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Aphid + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.p, file = "mod8.re.ln.p.RData")
mod8.re.ln.q <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.q, file = "mod8.re.ln.q.RData")
mod8.re.ln.r <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Aphid + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.r, file = "mod8.re.ln.r.RData")
mod8.re.ln.s <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Aphid + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.s, file = "mod8.re.ln.s.RData")
mod8.re.ln.t <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Aphid  + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.t, file = "mod8.re.ln.t.RData")
mod8.re.ln.u <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.u, file = "mod8.re.ln.u.RData")
mod8.re.ln.v <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Aphid + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.v, file = "mod8.re.ln.v.RData")
mod8.re.ln.w <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.w, file = "mod8.re.ln.w.RData")
mod8.re.ln.x <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Aphid + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.x, file = "mod8.re.ln.x.RData")
mod8.re.ln.y <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.y, file = "mod8.re.ln.y.RData")
mod8.re.ln.z <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.z, file = "mod8.re.ln.z.RData")
mod8.re.ln.aa <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Aphid + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.aa, file = "mod8.re.ln.aa.RData")
mod8.re.ln.ab <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.ab, file = "mod8.re.ln.ab.RData")

mod9.ln <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod8.re.ln.a, file = "mod9.ln.RData")
mod9.re.ln.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.a, file = "mod9.re.ln.a.RData")
mod9.re.ln.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.b, file = "mod9.re.ln.b.RData")
mod9.re.ln.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.c, file = "mod9.re.ln.c.RData")
mod9.re.ln.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.d, file = "mod9.re.ln.d.RData")
mod9.re.ln.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.e, file = "mod9.re.ln.e.RData")
mod9.re.ln.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.f, file = "mod9.re.ln.f.RData")
mod9.re.ln.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.g, file = "mod9.re.ln.g.RData")
mod9.re.ln.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.h, file = "mod9.re.ln.h.RData")
mod9.re.ln.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.i, file = "mod9.re.ln.i.RData")
mod9.re.ln.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.j, file = "mod9.re.ln.j.RData")
mod9.re.ln.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.k, file = "mod9.re.ln.k.RData")
mod9.re.ln.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.l, file = "mod9.re.ln.l.RData")
mod9.re.ln.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.m, file = "mod9.re.ln.m.RData")
mod9.re.ln.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.n, file = "mod9.re.ln.n.RData")
mod9.re.ln.o <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.o, file = "mod9.re.ln.o.RData")
mod9.re.ln.p <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.p, file = "mod9.re.ln.p.RData")
mod9.re.ln.q <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.q, file = "mod9.re.ln.q.RData")
mod9.re.ln.r <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Aphid + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.r, file = "mod9.re.ln.r.RData")
mod9.re.ln.s <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.s, file = "mod9.re.ln.s.RData")
mod9.re.ln.t <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Aphid  + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.t, file = "mod9.re.ln.t.RData")
mod9.re.ln.u <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.u, file = "mod9.re.ln.u.RData")
mod9.re.ln.v <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Aphid + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.v, file = "mod9.re.ln.v.RData")
mod9.re.ln.w <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.w, file = "mod9.re.ln.w.RData")
mod9.re.ln.x <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.x, file = "mod9.re.ln.x.RData")
mod9.re.ln.y <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.y, file = "mod9.re.ln.y.RData")
mod9.re.ln.z <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.z, file = "mod9.re.ln.z.RData")
mod9.re.ln.aa <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.aa, file = "mod9.re.ln.aa.RData")
mod9.re.ln.ab <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod9.re.ln.ab, file = "mod9.re.ln.ab.RData")

mod10.ln <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.ln, file = "mod10.ln.RData")
mod10.re.ln.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.a, file = "mod10.re.ln.a.RData")
mod10.re.ln.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.b, file = "mod10.re.ln.b.RData")
mod10.re.ln.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.c, file = "mod10.re.ln.c.RData")
mod10.re.ln.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.d, file = "mod10.re.ln.d.RData")
mod10.re.ln.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.e, file = "mod10.re.ln.e.RData")
mod10.re.ln.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.f, file = "mod10.re.ln.f.RData")
mod10.re.ln.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.g, file = "mod10.re.ln.g.RData")
mod10.re.ln.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.h, file = "mod10.re.ln.h.RData")
mod10.re.ln.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.i, file = "mod10.re.ln.i.RData")
mod10.re.ln.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.j, file = "mod10.re.ln.j.RData")
mod10.re.ln.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.k, file = "mod10.re.ln.k.RData")
mod10.re.ln.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.l, file = "mod10.re.ln.l.RData")
mod10.re.ln.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.m, file = "mod10.re.ln.m.RData")
mod10.re.ln.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.n, file = "mod10.re.ln.n.RData")
mod10.re.ln.o <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Aphid + Endophyte + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.o, file = "mod10.re.ln.o.RData")
mod10.re.ln.p <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Aphid + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.p, file = "mod10.re.ln.p.RData")
mod10.re.ln.q <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Endophyte + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.q, file = "mod10.re.ln.q.RData")
mod10.re.ln.r <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Aphid + Endophyte + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.r, file = "mod10.re.ln.r.RData")
mod10.re.ln.s <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Aphid + Endophyte + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.s, file = "mod10.re.ln.s.RData")
mod10.re.ln.t <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Aphid  + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.t, file = "mod10.re.ln.t.RData")
mod10.re.ln.u <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Endophyte + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.u, file = "mod10.re.ln.u.RData")
mod10.re.ln.v <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Aphid + Endophyte + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.v, file = "mod10.re.ln.v.RData")
mod10.re.ln.w <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.w, file = "mod10.re.ln.w.RData")
mod10.re.ln.x <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Aphid + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.x, file = "mod10.re.ln.x.RData")
mod10.re.ln.y <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Endophyte + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.y, file = "mod10.re.ln.y.RData")
mod10.re.ln.z <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.z, file = "mod10.re.ln.z.RData")
mod10.re.ln.aa <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Aphid + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.aa, file = "mod10.re.ln.aa.RData")
mod10.re.ln.ab <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Endophyte + Aphid:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod10.re.ln.ab, file = "mod10.re.ln.ab.RData")

mod11.ln <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.ln, file = "mod11.ln.RData")
mod11.re.ln.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.a, file = "mod11.re.ln.a.RData")
mod11.re.ln.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.b, file = "mod11.re.ln.b.RData")
mod11.re.ln.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.c, file = "mod11.re.ln.c.RData")
mod11.re.ln.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.d, file = "mod11.re.ln.d.RData")
mod11.re.ln.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.e, file = "mod11.re.ln.e.RData")
mod11.re.ln.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.f, file = "mod11.re.ln.f.RData")
mod11.re.ln.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.g, file = "mod11.re.ln.g.RData")
mod11.re.ln.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.h, file = "mod11.re.ln.h.RData")
mod11.re.ln.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.i, file = "mod11.re.ln.i.RData")
mod11.re.ln.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.j, file = "mod11.re.ln.j.RData")
mod11.re.ln.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.k, file = "mod11.re.ln.k.RData")
mod11.re.ln.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.l, file = "mod11.re.ln.l.RData")
mod11.re.ln.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.m, file = "mod11.re.ln.m.RData")
mod11.re.ln.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.n, file = "mod11.re.ln.n.RData")
mod11.re.ln.o <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.o, file = "mod11.re.ln.o.RData")
mod11.re.ln.p <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.p, file = "mod11.re.ln.p.RData")
mod11.re.ln.q <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.q, file = "mod11.re.ln.q.RData")
mod11.re.ln.r <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.r, file = "mod11.re.ln.r.RData")
mod11.re.ln.s <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.s, file = "mod11.re.ln.s.RData")
mod11.re.ln.t <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid  + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.t, file = "mod11.re.ln.t.RData")
mod11.re.ln.u <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.u, file = "mod11.re.ln.u.RData")
mod11.re.ln.v <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.v, file = "mod11.re.ln.v.RData")
mod11.re.ln.w <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.w, file = "mod11.re.ln.w.RData")
mod11.re.ln.x <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.x, file = "mod11.re.ln.x.RData")
mod11.re.ln.y <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.y, file = "mod11.re.ln.y.RData")
mod11.re.ln.z <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.z, file = "mod11.re.ln.z.RData")
mod11.re.ln.aa <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.aa, file = "mod11.re.ln.aa.RData")
mod11.re.ln.ab <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Endophyte + Ozone:Aphid | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ab, file = "mod11.re.ln.ab.RData")

mod11.re.ln.ac <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ac, file = "mod11.re.ln.ac.RData")
mod11.re.ln.ad <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ad, file = "mod11.re.ln.ad.RData")
mod11.re.ln.ae <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ae, file = "mod11.re.ln.ae.RData")
mod11.re.ln.af <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.af, file = "mod11.re.ln.af.RData")
mod11.re.ln.ag <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte + Ozone:Aphid+  Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ag, file = "mod11.re.ln.ag.RData")
mod11.re.ln.ah <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid  + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ah, file = "mod11.re.ln.ah.RData")
mod11.re.ln.ai <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ai, file = "mod11.re.ln.ai.RData")
mod11.re.ln.aj <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.aj, file = "mod11.re.ln.aj.RData")
mod11.re.ln.ak <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ak, file = "mod11.re.ln.ak.RData")
mod11.re.ln.al <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.al, file = "mod11.re.ln.al.RData")
mod11.re.ln.am <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.am, file = "mod11.re.ln.am.RData")
mod11.re.ln.an <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.an, file = "mod11.re.ln.an.RData")
mod11.re.ln.ao <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ao, file = "mod11.re.ln.ao.RData")
mod11.re.ln.ap <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ap, file = "mod11.re.ln.ap.RData")

mod11.re.ln.aq <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.aq, file = "mod11.re.ln.aq.RData")
mod11.re.ln.ar <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ar, file = "mod11.re.ln.ar.RData")
mod11.re.ln.as <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.as, file = "mod11.re.ln.as.RData")
mod11.re.ln.at <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.at, file = "mod11.re.ln.at.RData")
mod11.re.ln.au <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.au, file = "mod11.re.ln.au.RData")
mod11.re.ln.av <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid  + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.av, file = "mod11.re.ln.av.RData")
mod11.re.ln.aw <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.aw, file = "mod11.re.ln.aw.RData")
mod11.re.ln.ax <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ax, file = "mod11.re.ln.ax.RData")
mod11.re.ln.ay <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ay, file = "mod11.re.ln.ay.RData")
mod11.re.ln.az <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.az, file = "mod11.re.ln.az.RData")
mod11.re.ln.ba <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.ba, file = "mod11.re.ln.ba.RData")
mod11.re.ln.bb <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.bb, file = "mod11.re.ln.bb.RData")
mod11.re.ln.bc <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.bc, file = "mod11.re.ln.bc.RData")
mod11.re.ln.bd <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Endophyte + Ozone:Endophyte | Year), family = lognormal, iter = 30000, data = db, cores = 4)
save(mod11.re.ln.bd, file = "mod11.re.ln.bd.RData")

mod12.ln <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid, family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.ln, file = "mod12.ln.RData")
mod12.re.ln.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.a, file = "mod12.re.ln.a.RData")
mod12.re.ln.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.b, file = "mod12.re.ln.b.RData")
mod12.re.ln.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.c, file = "mod12.re.ln.c.RData")
mod12.re.ln.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.d, file = "mod12.re.ln.d.RData")
mod12.re.ln.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.e, file = "mod12.re.ln.e.RData")
mod12.re.ln.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Aphid | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.f, file = "mod12.re.ln.f.RData")
mod12.re.ln.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Aphid | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.g, file = "mod12.re.ln.g.RData")
mod12.re.ln.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone + Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.h, file = "mod12.re.ln.h.RData")
mod12.re.ln.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone + Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.i, file = "mod12.re.ln.i.RData")
mod12.re.ln.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone + Aphid | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.j, file = "mod12.re.ln.j.RData")
mod12.re.ln.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone + Aphid | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.k, file = "mod12.re.ln.k.RData")
mod12.re.ln.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone + Endophyte + Ozone:Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.l, file = "mod12.re.ln.l.RData")
mod12.re.ln.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone + Endophyte + Ozone:Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.m, file = "mod12.re.ln.m.RData")
mod12.re.ln.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone + Endophyte + Ozone:Aphid | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.n, file = "mod12.re.ln.n.RData")
mod12.re.ln.o <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone + Endophyte + Ozone:Aphid | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.o, file = "mod12.re.ln.o.RData")
mod12.re.ln.p <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Aphid + Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.p, file = "mod12.re.ln.p.RData")
mod12.re.ln.q <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Aphid + Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.q, file = "mod12.re.ln.q.RData")
mod12.re.ln.r <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Aphid + Endophyte + Aphid:Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.r, file = "mod12.re.ln.r.RData")
mod12.re.ln.s <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Aphid + Endophyte + Aphid:Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.s, file = "mod12.re.ln.s.RData")
mod12.re.ln.t <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone + Endophyte + Aphid + Ozone:Endophyte + Ozone:Aphid + Aphid:Endophyte + Ozone:Aphid:Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.t, file = "mod12.re.ln.t.RData")
mod12.re.ln.u <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone + Endophyte + Aphid + Ozone:Endophyte + Ozone:Aphid + Aphid:Endophyte + Ozone:Aphid:Endophyte | Year) , family = lognormal, iter = 30000, data = db, cores = 4)
save(mod12.re.ln.u, file = "mod12.re.ln.u.RData")

mod0.g <- brm(Biomass ~ 1, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod0.g, file = "mod0.g.RData")
mod1.g <- brm(Biomass ~ Ozone, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod1.g, file = "mod1.g.RData")
mod1.re.g.a <- brm(Biomass ~ Ozone + (1 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod1.re.g.a, file = "mod1.g.a.RData")
mod1.re.g.b <- brm(Biomass ~ Ozone + (0 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod1.re.g.b, file = "mod1.g.b.RData")
mod1.re.g.c <- brm(Biomass ~ Ozone + (1 | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod1.re.g.c, file = "mod1.g.c.RData")

mod2.g <- brm(Biomass ~ Aphid, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod2.g, file = "mod2.g.RData")
mod2.re.g.a <- brm(Biomass ~ Aphid + (1 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod2.re.g.a, file = "mod2.re.g.a.RData")
mod2.re.g.b <- brm(Biomass ~ Aphid + (0 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod2.re.g.b, file = "mod2.re.g.b.RData")
mod2.re.g.c <- brm(Biomass ~ Aphid + (1 | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod2.re.g.c, file = "mod2.re.g.c.RData")

mod3.g <- brm(Biomass ~ Endophyte, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod3.g, file = "mod3.g.RData")
mod3.re.g.a <- brm(Biomass ~ Endophyte + (1 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod3.re.g.a, file = "mod3.re.g.a.RData")
mod3.re.g.b <- brm(Biomass ~ Endophyte + (0 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod3.re.g.b, file = "mod3.re.g.b.RData")
mod3.re.g.c <- brm(Biomass ~ Endophyte + (1 | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod3.re.g.c, file = "mod3.re.g.c.RData")

mod4.g <- brm(Biomass ~ Ozone + Aphid, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod4.g, file = "mod4.g.RData")
mod4.re.g.a <- brm(Biomass ~ Ozone + Aphid + (1 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod4.re.g.a, file = "mod4.re.g.a.RData")
mod4.re.g.b <- brm(Biomass ~ Ozone + Aphid + (0 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod4.re.g.b, file = "mod4.re.g.b.RData")
mod4.re.g.c <- brm(Biomass ~ Ozone + Aphid + (1 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod4.re.g.c, file = "mod4.re.g.c.RData")
mod4.re.g.d <- brm(Biomass ~ Ozone + Aphid + (0 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod4.re.g.d, file = "mod4.re.g.d.RData")
mod4.re.g.e <- brm(Biomass ~ Ozone + Aphid + (1 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod4.re.g.e, file = "mod4.re.g.e.RData")
mod4.re.g.f <- brm(Biomass ~ Ozone + Aphid + (0 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod4.re.g.f, file = "mod4.re.g.f.RData")
mod4.re.g.g <- brm(Biomass ~ Ozone + Aphid + (1 | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod4.re.g.g, file = "mod4.re.g.g.RData")

mod5.g <- brm(Biomass ~ Ozone + Endophyte, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod5.g, file = "mod5.g.RData")
mod5.re.g.a <- brm(Biomass ~ Ozone + Endophyte + (1 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod5.re.g.a, file = "mod5.re.g.a.RData")
mod5.re.g.b <- brm(Biomass ~ Ozone + Endophyte + (0 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod5.re.g.b, file = "mod5.re.g.b.RData")
mod5.re.g.c <- brm(Biomass ~ Ozone + Endophyte + (1 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod5.re.g.c, file = "mod5.re.g.c.RData")
mod5.re.g.d <- brm(Biomass ~ Ozone + Endophyte + (0 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod5.re.g.d, file = "mod5.re.g.d.RData")
mod5.re.g.e <- brm(Biomass ~ Ozone + Endophyte + (1 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod5.re.g.e, file = "mod5.re.g.e.RData")
mod5.re.g.f <- brm(Biomass ~ Ozone + Endophyte + (0 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod5.re.g.f, file = "mod5.re.g.f.RData")
mod5.re.g.g <- brm(Biomass ~ Ozone + Endophyte + (1 | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod5.re.g.g, file = "mod5.re.g.g.RData")

mod6.g <- brm(Biomass ~ Aphid + Endophyte, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod6.g, file = "mod6.g.RData")
mod6.re.g.a <- brm(Biomass ~ Aphid + Endophyte + (1 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod6.re.g.a, file = "mod6.re.g.a.RData")
mod6.re.g.b <- brm(Biomass ~ Aphid + Endophyte + (0 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod6.re.g.b, file = "mod6.re.g.b.RData")
mod6.re.g.c <- brm(Biomass ~ Aphid + Endophyte + (1 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod6.re.g.c, file = "mod6.re.g.c.RData")
mod6.re.g.d <- brm(Biomass ~ Aphid + Endophyte + (0 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod6.re.g.d, file = "mod6.re.g.d.RData")
mod6.re.g.e <- brm(Biomass ~ Aphid + Endophyte + (1 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod6.re.g.e, file = "mod6.re.g.e.RData")
mod6.re.g.f <- brm(Biomass ~ Aphid + Endophyte + (0 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod6.re.g.f, file = "mod6.re.g.f.RData")
mod6.re.g.g <- brm(Biomass ~ Aphid + Endophyte + (1 | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod6.re.g.g, file = "mod6.re.g.g.RData")

mod7.g <- brm(Biomass ~ Ozone + Aphid + Endophyte, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.g, file = "mod7.g.RData")
mod7.re.g.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Ozone + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.a, file = "mod7.re.g.a.RData")
mod7.re.g.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.b, file = "mod7.re.g.b.RData")
mod7.re.g.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.c, file = "mod7.re.g.c.RData")
mod7.re.g.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.d, file = "mod7.re.g.d.RData")
mod7.re.g.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Ozone + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.e, file = "mod7.re.g.e.RData")
mod7.re.g.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.f, file = "mod7.re.g.f.RData")
mod7.re.g.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.g, file = "mod7.re.g.g.RData")
mod7.re.g.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.h, file = "mod7.re.g.h.RData")
mod7.re.g.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.i, file = "mod7.re.g.i.RData")
mod7.re.g.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.j, file = "mod7.re.g.j.RData")
mod7.re.g.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + (1 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.k, file = "mod7.re.g.k.RData")
mod7.re.g.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.l, file = "mod7.re.g.l.RData")
mod7.re.g.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.m, file = "mod7.re.g.m.RData")
mod7.re.g.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + (0 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod7.re.g.n, file = "mod7.re.g.n.RData")


mod8.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.g, file = "mod8.g.RData")
mod8.re.g.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.a, file = "mod8.re.g.a.RData")
mod8.re.g.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.b, file = "mod8.re.g.b.RData")
mod8.re.g.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.c, file = "mod8.re.g.c.RData")
mod8.re.g.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.d, file = "mod8.re.g.d.RData")
mod8.re.g.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.e, file = "mod8.re.g.e.RData")
mod8.re.g.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.f, file = "mod8.re.g.f.RData")
mod8.re.g.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.f, file = "mod8.re.g.f.RData")
mod8.re.g.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.h, file = "mod8.re.g.h.RData")
mod8.re.g.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.i, file = "mod8.re.g.i.RData")
mod8.re.g.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.j, file = "mod8.re.g.j.RData")
mod8.re.g.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.k, file = "mod8.re.g.k.RData")
mod8.re.g.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.l, file = "mod8.re.g.l.RData")
mod8.re.g.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.m, file = "mod8.re.g.m.RData")
mod8.re.g.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.n, file = "mod8.re.g.n.RData")
mod8.re.g.o <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Aphid + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.o, file = "mod8.re.g.o.RData")
mod8.re.g.p <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Aphid + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.p, file = "mod8.re.g.p.RData")
mod8.re.g.q <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.q, file = "mod8.re.g.q.RData")
mod8.re.g.r <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Aphid + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.r, file = "mod8.re.g.r.RData")
mod8.re.g.s <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Aphid + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.s, file = "mod8.re.g.s.RData")
mod8.re.g.t <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Aphid  + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.t, file = "mod8.re.g.t.RData")
mod8.re.g.u <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.u, file = "mod8.re.g.u.RData")
mod8.re.g.v <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Aphid + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.v, file = "mod8.re.g.v.RData")
mod8.re.g.w <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Ozone + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.w, file = "mod8.re.g.w.RData")
mod8.re.g.x <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Aphid + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.x, file = "mod8.re.g.x.RData")
mod8.re.g.y <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (1 + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.y, file = "mod8.re.g.y.RData")
mod8.re.g.z <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Ozone + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.z, file = "mod8.re.g.z.RData")
mod8.re.g.aa <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Aphid + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.aa, file = "mod8.re.g.aa.RData")
mod8.re.g.ab <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + (0 + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.ab, file = "mod8.re.g.ab.RData")

mod9.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod8.re.g.a, file = "mod9.g.RData")
mod9.re.g.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.a, file = "mod9.re.g.a.RData")
mod9.re.g.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.b, file = "mod9.re.g.b.RData")
mod9.re.g.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.c, file = "mod9.re.g.c.RData")
mod9.re.g.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.d, file = "mod9.re.g.d.RData")
mod9.re.g.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.e, file = "mod9.re.g.e.RData")
mod9.re.g.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.f, file = "mod9.re.g.f.RData")
mod9.re.g.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.g, file = "mod9.re.g.g.RData")
mod9.re.g.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.h, file = "mod9.re.g.h.RData")
mod9.re.g.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.i, file = "mod9.re.g.i.RData")
mod9.re.g.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.j, file = "mod9.re.g.j.RData")
mod9.re.g.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.k, file = "mod9.re.g.k.RData")
mod9.re.g.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.l, file = "mod9.re.g.l.RData")
mod9.re.g.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.m, file = "mod9.re.g.m.RData")
mod9.re.g.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.n, file = "mod9.re.g.n.RData")
mod9.re.g.o <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.o, file = "mod9.re.g.o.RData")
mod9.re.g.p <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.p, file = "mod9.re.g.p.RData")
mod9.re.g.q <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.q, file = "mod9.re.g.q.RData")
mod9.re.g.r <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Aphid + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.r, file = "mod9.re.g.r.RData")
mod9.re.g.s <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.s, file = "mod9.re.g.s.RData")
mod9.re.g.t <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Aphid  + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.t, file = "mod9.re.g.t.RData")
mod9.re.g.u <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.u, file = "mod9.re.g.u.RData")
mod9.re.g.v <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Aphid + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.v, file = "mod9.re.g.v.RData")
mod9.re.g.w <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Ozone + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.w, file = "mod9.re.g.w.RData")
mod9.re.g.x <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.x, file = "mod9.re.g.x.RData")
mod9.re.g.y <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (1 + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.y, file = "mod9.re.g.y.RData")
mod9.re.g.z <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Ozone + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.z, file = "mod9.re.g.z.RData")
mod9.re.g.aa <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.aa, file = "mod9.re.g.aa.RData")
mod9.re.g.ab <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Endophyte + (0 + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod9.re.g.ab, file = "mod9.re.g.ab.RData")

mod10.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.g, file = "mod10.g.RData")
mod10.re.g.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.a, file = "mod10.re.g.a.RData")
mod10.re.g.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.b, file = "mod10.re.g.b.RData")
mod10.re.g.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.c, file = "mod10.re.g.c.RData")
mod10.re.g.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.d, file = "mod10.re.g.d.RData")
mod10.re.g.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.e, file = "mod10.re.g.e.RData")
mod10.re.g.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.f, file = "mod10.re.g.f.RData")
mod10.re.g.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.g, file = "mod10.re.g.g.RData")
mod10.re.g.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.h, file = "mod10.re.g.h.RData")
mod10.re.g.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.i, file = "mod10.re.g.i.RData")
mod10.re.g.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.j, file = "mod10.re.g.j.RData")
mod10.re.g.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.k, file = "mod10.re.g.k.RData")
mod10.re.g.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.l, file = "mod10.re.g.l.RData")
mod10.re.g.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.m, file = "mod10.re.g.m.RData")
mod10.re.g.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.n, file = "mod10.re.g.n.RData")
mod10.re.g.o <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Aphid + Endophyte + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.o, file = "mod10.re.g.o.RData")
mod10.re.g.p <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Aphid + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.p, file = "mod10.re.g.p.RData")
mod10.re.g.q <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Endophyte + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.q, file = "mod10.re.g.q.RData")
mod10.re.g.r <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Aphid + Endophyte + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.r, file = "mod10.re.g.r.RData")
mod10.re.g.s <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Aphid + Endophyte + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.s, file = "mod10.re.g.s.RData")
mod10.re.g.t <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Aphid  + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.t, file = "mod10.re.g.t.RData")
mod10.re.g.u <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Endophyte + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.u, file = "mod10.re.g.u.RData")
mod10.re.g.v <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Aphid + Endophyte + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.v, file = "mod10.re.g.v.RData")
mod10.re.g.w <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Ozone + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.w, file = "mod10.re.g.w.RData")
mod10.re.g.x <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Aphid + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.x, file = "mod10.re.g.x.RData")
mod10.re.g.y <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (1 + Endophyte + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.y, file = "mod10.re.g.y.RData")
mod10.re.g.z <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Ozone + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.z, file = "mod10.re.g.z.RData")
mod10.re.g.aa <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Aphid + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.aa, file = "mod10.re.g.aa.RData")
mod10.re.g.ab <- brm(Biomass ~ Ozone + Aphid + Endophyte + Aphid:Endophyte + (0 + Endophyte + Aphid:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod10.re.g.ab, file = "mod10.re.g.ab.RData")

mod11.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.g, file = "mod11.g.RData")
mod11.re.g.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.a, file = "mod11.re.g.a.RData")
mod11.re.g.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.b, file = "mod11.re.g.b.RData")
mod11.re.g.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.c, file = "mod11.re.g.c.RData")
mod11.re.g.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.d, file = "mod11.re.g.d.RData")
mod11.re.g.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.e, file = "mod11.re.g.e.RData")
mod11.re.g.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.f, file = "mod11.re.g.f.RData")
mod11.re.g.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.g, file = "mod11.re.g.g.RData")
mod11.re.g.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.h, file = "mod11.re.g.h.RData")
mod11.re.g.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.i, file = "mod11.re.g.i.RData")
mod11.re.g.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.j, file = "mod11.re.g.j.RData")
mod11.re.g.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.k, file = "mod11.re.g.k.RData")
mod11.re.g.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.l, file = "mod11.re.g.l.RData")
mod11.re.g.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.m, file = "mod11.re.g.m.RData")
mod11.re.g.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.n, file = "mod11.re.g.n.RData")
mod11.re.g.o <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.o, file = "mod11.re.g.o.RData")
mod11.re.g.p <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.p, file = "mod11.re.g.p.RData")
mod11.re.g.q <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.q, file = "mod11.re.g.q.RData")
mod11.re.g.r <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.r, file = "mod11.re.g.r.RData")
mod11.re.g.s <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.s, file = "mod11.re.g.s.RData")
mod11.re.g.t <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid  + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.t, file = "mod11.re.g.t.RData")
mod11.re.g.u <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.u, file = "mod11.re.g.u.RData")
mod11.re.g.v <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.v, file = "mod11.re.g.v.RData")
mod11.re.g.w <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.w, file = "mod11.re.g.w.RData")
mod11.re.g.x <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.x, file = "mod11.re.g.x.RData")
mod11.re.g.y <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.y, file = "mod11.re.g.y.RData")
mod11.re.g.z <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.z, file = "mod11.re.g.z.RData")
mod11.re.g.aa <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.aa, file = "mod11.re.g.aa.RData")
mod11.re.g.ab <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Endophyte + Ozone:Aphid | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ab, file = "mod11.re.g.ab.RData")

mod11.re.g.ac <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ac, file = "mod11.re.g.ac.RData")
mod11.re.g.ad <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ad, file = "mod11.re.g.ad.RData")
mod11.re.g.ae <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ae, file = "mod11.re.g.ae.RData")
mod11.re.g.af <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.af, file = "mod11.re.g.af.RData")
mod11.re.g.ag <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte + Ozone:Aphid+  Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ag, file = "mod11.re.g.ag.RData")
mod11.re.g.ah <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid  + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ah, file = "mod11.re.g.ah.RData")
mod11.re.g.ai <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ai, file = "mod11.re.g.ai.RData")
mod11.re.g.aj <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.aj, file = "mod11.re.g.aj.RData")
mod11.re.g.ak <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ak, file = "mod11.re.g.ak.RData")
mod11.re.g.al <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.al, file = "mod11.re.g.al.RData")
mod11.re.g.am <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.am, file = "mod11.re.g.am.RData")
mod11.re.g.an <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.an, file = "mod11.re.g.an.RData")
mod11.re.g.ao <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ao, file = "mod11.re.g.ao.RData")
mod11.re.g.ap <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Endophyte + Ozone:Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ap, file = "mod11.re.g.ap.RData")

mod11.re.g.aq <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.aq, file = "mod11.re.g.aq.RData")
mod11.re.g.ar <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ar, file = "mod11.re.g.ar.RData")
mod11.re.g.as <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.as, file = "mod11.re.g.as.RData")
mod11.re.g.at <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.at, file = "mod11.re.g.at.RData")
mod11.re.g.au <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.au, file = "mod11.re.g.au.RData")
mod11.re.g.av <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Aphid  + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.av, file = "mod11.re.g.av.RData")
mod11.re.g.aw <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.aw, file = "mod11.re.g.aw.RData")
mod11.re.g.ax <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ax, file = "mod11.re.g.ax.RData")
mod11.re.g.ay <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Ozone + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ay, file = "mod11.re.g.ay.RData")
mod11.re.g.az <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.az, file = "mod11.re.g.az.RData")
mod11.re.g.ba <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (1 + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.ba, file = "mod11.re.g.ba.RData")
mod11.re.g.bb <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Ozone + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.bb, file = "mod11.re.g.bb.RData")
mod11.re.g.bc <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Aphid + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.bc, file = "mod11.re.g.bc.RData")
mod11.re.g.bd <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + (0 + Endophyte + Ozone:Endophyte | Year), family = gaussian, iter = 30000, data = db, cores = 4)
save(mod11.re.g.bd, file = "mod11.re.g.bd.RData")

mod12.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid, family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.g, file = "mod12.g.RData")
mod12.re.g.a <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.a, file = "mod12.re.g.a.RData")
mod12.re.g.b <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.b, file = "mod12.re.g.b.RData")
mod12.re.g.c <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.c, file = "mod12.re.g.c.RData")
mod12.re.g.d <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.d, file = "mod12.re.g.d.RData")
mod12.re.g.e <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.e, file = "mod12.re.g.e.RData")
mod12.re.g.f <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Aphid | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.f, file = "mod12.re.g.f.RData")
mod12.re.g.g <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Aphid | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.g, file = "mod12.re.g.g.RData")
mod12.re.g.h <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone + Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.h, file = "mod12.re.g.h.RData")
mod12.re.g.i <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone + Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.i, file = "mod12.re.g.i.RData")
mod12.re.g.j <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone + Aphid | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.j, file = "mod12.re.g.j.RData")
mod12.re.g.k <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone + Aphid | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.k, file = "mod12.re.g.k.RData")
mod12.re.g.l <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone + Endophyte + Ozone:Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.l, file = "mod12.re.g.l.RData")
mod12.re.g.m <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone + Endophyte + Ozone:Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.m, file = "mod12.re.g.m.RData")
mod12.re.g.n <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone + Endophyte + Ozone:Aphid | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.n, file = "mod12.re.g.n.RData")
mod12.re.g.o <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone + Endophyte + Ozone:Aphid | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.o, file = "mod12.re.g.o.RData")
mod12.re.g.p <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Aphid + Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.p, file = "mod12.re.g.p.RData")
mod12.re.g.q <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Aphid + Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.q, file = "mod12.re.g.q.RData")
mod12.re.g.r <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Aphid + Endophyte + Aphid:Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.r, file = "mod12.re.g.r.RData")
mod12.re.g.s <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Aphid + Endophyte + Aphid:Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.s, file = "mod12.re.g.s.RData")
mod12.re.g.t <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (1 + Ozone + Endophyte + Aphid + Ozone:Endophyte + Ozone:Aphid + Aphid:Endophyte + Ozone:Aphid:Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.t, file = "mod12.re.g.t.RData")
mod12.re.g.u <- brm(Biomass ~ Ozone + Aphid + Endophyte + Ozone:Aphid + Ozone:Endophyte + Aphid:Endophyte + Ozone:Endophyte:Aphid + (0 + Ozone + Endophyte + Aphid + Ozone:Endophyte + Ozone:Aphid + Aphid:Endophyte + Ozone:Aphid:Endophyte | Year) , family = gaussian, iter = 30000, data = db, cores = 4)
save(mod12.re.g.u, file = "mod12.re.g.u.RData")

files <- list.files()
results <-sapply(files, function(x) mget(load(x)), simplify = TRUE)
df.loos <- data.frame(looic = rep(NA, length(files)), se = rep(NA, length(files)), modelo = rep(NA, length(files)))
loo_results <- list()
count <- 1
for( i in 1 : length(files)){
  loo_results[[i]] <- loo(results[[i]])
  df.loos$looic[i] <- loo_results[[i]]$estimates[3, 1]
  df.loos$se[i] <- loo_results[[i]]$estimates[3,2]
  files[[i]] <- gsub(".RData", "", files[[i]])
  df.loos$modelo[i] <- files[[i]]
  cat("count = ", count, "\n")
  count <- count + 1
}

p <- ggplot(data = df.loos, aes(x = reorder(modelo, looic), y = looic)) +
  labs(x = "Modelo", y = "LOOIC")+
  geom_point() +
  geom_errorbar(aes(ymin= looic - 2*se, ymax = looic + 2*se), width= 0.2) +
  theme(text = element_text(size = 10))

looics$w <- exp(-0.5*(looics$looic - min(looics$looic)))/sum(exp(-0.5*(looics$looic - min(looics$looic))))

x.i.1 <- c(0, 1)
x.i.2 <- c(0, 1)
x.i.3 <- c(0, 1)
z.i.1.  <- fitted(mod1, newdata= data.frame(Ozone = 1, Aphid = 1, Endophyte = 1), re_formula = NA)
z.i.1.b <- fitted(mod1, newdata= data.frame(Ozone = 1, Aphid = 1, Endophyte = 1), re_formula = NA)